name: build-and-push-docker

on:
  push:
    branches: master
    paths:
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: thanhleviet/monitor-release:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN_KEY }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.output.digest }}